-- 코드를 작성해주세요
SELECT ID,
    CASE 
        WHEN NTILE_GROUP = 1 THEN 'CRITICAL'
        WHEN NTILE_GROUP = 2 THEN 'HIGH'
        WHEN NTILE_GROUP = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID,
           NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NTILE_GROUP
    FROM ECOLI_DATA
) ranked_data
ORDER BY ID ASC;