-- 코드를 입력하세요
-- SELECT DATE_FORMAT(DATETIME, '%k') AS HOUR, COUNT(*) AS COUNT
-- FROM ANIMAL_OUTS
-- WHERE DATE_FORMAT(DATETIME, '%k') BETWEEN 9 AND 19
-- GROUP BY DATE_FORMAT(DATETIME, '%k')
-- ORDER BY DATE_FORMAT(DATETIME, '%k') ASC;

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR ASC;