-- 코드를 입력하세요
SELECT p.MEMBER_NAME, r.REVIEW_TEXT, 
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE p
JOIN REST_REVIEW r ON p.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID = (
    SELECT r2.MEMBER_ID
    FROM REST_REVIEW r2
    GROUP BY r2.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;