-- 코드를 입력하세요
WITH RentalCounts AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT 
    DATE_FORMAT(START_DATE, '%c') AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    CAR_ID IN (SELECT CAR_ID FROM RentalCounts)
    AND DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY 
    DATE_FORMAT(START_DATE, '%Y-%m'),
    CAR_ID
ORDER BY 
    MONTH(START_DATE) ASC,
    CAR_ID DESC;