-- 코드를 작성해주세요
SELECT SUM(hg.SCORE) AS SCORE, he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM HR_DEPARTMENT hd
JOIN HR_EMPLOYEES he ON hd.DEPT_ID = he.DEPT_ID
JOIN HR_GRADE hg ON he.EMP_NO = hg.EMP_NO
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;